name: Run Padel Script

on:
  workflow_dispatch: # Manuelles Auslösen des Workflows

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup von Python
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Skript ausführen mit Secrets
      - name: Run Python script
        env:
          MODE: cloud
          PLAYTOMIC_USERNAME: ${{ secrets.PLAYTOMIC_USERNAME }}
          PLAYTOMIC_PASSWORD: ${{ secrets.PLAYTOMIC_PASSWORD }}
          USERNAME_MAIL_SENDER: ${{ secrets.USERNAME_MAIL_SENDER }}
          PASSWORD_MAIL_SENDER: ${{ secrets.PASSWORD_MAIL_SENDER }}
        run: python main.py

      # Pushe aktualisierte Slots ins Repo  
      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add freie_plaetze_mannheim.csv freie_plaetze_ubstadt.csv
          git commit -m "Update freie_plaetze_mannheim.csv and freie_plaetze_ubstadt.csv via script"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
